### PR TITLE
Aligned "Database" blocks in the diagram

### PR DESCRIPTION
**Pull request by LorenzoBettini**
Nothing really serious but I spot misaligned "Database" blocks in the diagrams in the README...

### CODE REVIEW

**Comment by hamvocke** [comment]
Haha, I was obsessing about that one before 😀 I kept adding and removing padding but depending on what font your operating system's using, it just doesn't line up properly. My macbook renders the database icon as a proper emoji which doesn't have the fixed width I'm looking for. My Linux notebook doesn't render emoji so it looks alright there.

Here's a screenshot of the before and after state. What does it look like on your machine?
screen shot 2018-07-17 at 18 39 12

Thanks a lot for your contribution. It's the tiny details that count. Still don't know if your change made it better or worse. What do you think?

**Comment by LorenzoBettini** [comment]
Of course in my Linux machine it renders exactly the opposite (as in your Linux machine) ;)
feel free to close the PR.

**Comment by hamvocke** [comment]
Nah, you know what? You're right. Just because Mac OS doesn't render emoji in a fixed width we shouldn't aim to have a diagram that only somewhat looks good with that in mind when we could have a diagram that looks perfectly aligned with monospace fonts.

Merged. Big thank you!

**Comment by LorenzoBettini** [comment]
Holy words! ;)

**Pull request merged**
